
server:
  port: 8010
eureka:
  instance:
    hostname: myserver
  client:
    register-with-eureka: false
    fetch-registry: false
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

